const ActionType = {
  // Authentication
  SET_AUTH_USER: "SET_AUTH_USER",
  UNSET_AUTH_USER: "UNSET_AUTH_USER",

  // Users list
  RECEIVE_USERS: "RECEIVE_USERS",

  // Threads list
  RECEIVE_THREADS: "RECEIVE_THREADS",
  ADD_THREADS: "ADD_THREADS",

  // Thread details
  RECEIVE_THREAD_DETAIL: "RECEIVE_THREAD_DETAIL",
  CLEAR_THREAD_DETAIL: "CLEAR_THREAD_DETAIL",

  // Thread comments
  ADD_THREAD_COMMENT: "ADD_THREAD_COMMENT",

  // Voting on threads
  UP_VOTE_THREAD: "UP_VOTE_THREAD",
  DOWN_VOTE_THREAD: "DOWN_VOTE_THREAD",
  NEUTRAL_VOTE_THREAD: "NEUTRAL_VOTE_THREAD",

  // Voting on comments
  UP_VOTE_COMMENT: "UP_VOTE_COMMENT",
  DOWN_VOTE_COMMENT: "DOWN_VOTE_COMMENT",
  NEUTRAL_VOTE_COMMENT: "NEUTRAL_VOTE_COMMENT",

  // Leaderboard data
  RECEIVE_LEADERBOARD: "RECEIVE_LEADERBOARD",

  // UI loading state
  SET_IS_PRELOAD: "SET_IS_PRELOAD",
};

export default ActionType;
